#!/usr/bin/with-contenv sh
echo >&2 "starting APRCoinD"
HOME=/home/aprcoin

#reindex if reindex file found

for file in /root/reindex
do
if [ -f $file ]; then
        printf "reindex file detected, starting aprcoind with -reindex\n"
        rm -fvr /root/reindex
        sudo -u aprcoin aprcoind -reindex
else
        printf "reindex file not detected, starting aprcoind\n"
        sudo -u aprcoin aprcoind
fi
done
